// Mock the GoogleGenerativeAI library before importing backend files
import { GoogleGenerativeAI } from '@google/generative-ai';

GoogleGenerativeAI.prototype.getGenerativeModel = function (options) {
  return {
    generateContent: async function (prompt) {
      let textVal = '{}';
      if (prompt.includes('User prompt:')) {
        // Mock structured parser return
        textVal = JSON.stringify({
          isConversational: false,
          categories: ['Main'],
          cuisine: 'Nyonya',
          priceRange: '$$',
          isHalal: true,
          keywords: ['spicy'],
          isItinerary: false,
          findHiddenGems: false,
          intent: 'halal nyonya food'
        });
      } else {
        textVal = 'This is a mock XAI explanation generated by Gemini.';
      }
      return {
        response: {
          text: () => textVal
        }
      };
    }
  };
};

import express from 'express';
import dotenv from 'dotenv';
import chatRoutes from '../src/routes/chat.js';
import prisma from '../src/db/prisma.js';

dotenv.config();

async function main() {
  console.log('=== RECOMMENDATION RANKING BY MATCH PERCENTAGE TEST ===\n');

  // Verify that USE_MOCK_DB is false or we have a DB connection
  const useMock = process.env.USE_MOCK_DB !== 'false';
  console.log(`Environment: ${useMock ? 'Mock DB Mode' : 'PostgreSQL DB Mode'}`);

  // Spin up a mini test server
  const app = express();
  app.use(express.json());
  app.use('/api/chat', chatRoutes);

  const PORT = 5099;
  const server = app.listen(PORT, async () => {
    console.log(`Test server listening on port ${PORT}`);

    try {
      // Make a simulated request to POST /api/chat
      const requestPayload = {
        message: 'halal nyonya food',
        userLat: 2.1945,
        userLng: 102.2468,
        history: []
      };

      console.log('Sending request to /api/chat with payload:', JSON.stringify(requestPayload));
      
      const response = await fetch(`http://localhost:${PORT}/api/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestPayload)
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      const result = await response.json();
      const restaurants = result.restaurants || [];

      console.log(`\nReceived ${restaurants.length} recommendations:`);
      console.table(restaurants.map((r, i) => ({
        Rank: i + 1,
        Name: r.name,
        Category: r.category,
        Cuisine: r.cuisine,
        Rating: `${r.rating}★`,
        Distance: `${r.distance} km`,
        'Match %': `${r.matchPercentage}%`,
        Halal: r.isHalal ? 'Yes' : 'No'
      })));

      // Assert that recommendations are sorted by matchPercentage descending
      console.log('\n--- VERIFYING RANKING ASSERTIONS ---');
      let pass = true;
      for (let i = 0; i < restaurants.length - 1; i++) {
        const current = restaurants[i];
        const next = restaurants[i + 1];

        console.log(`Checking Rank #${i + 1} (${current.matchPercentage}%) vs Rank #${i + 2} (${next.matchPercentage}%)`);
        
        if (current.matchPercentage < next.matchPercentage) {
          console.error(`❌ FAIL: Rank #${i + 1} has lower match percentage than Rank #${i + 2}!`);
          pass = false;
        } else if (current.matchPercentage === next.matchPercentage) {
          // Tie-breaker check: distance should be ascending
          console.log(`  Tie-breaker check: Rank #${i + 1} distance (${current.distance} km) vs Rank #${i + 2} distance (${next.distance} km)`);
          if (current.distance > next.distance) {
            console.error(`❌ FAIL: Distance tie-breaker failed! Rank #${i + 1} is further than Rank #${i + 2}.`);
            pass = false;
          } else {
            console.log(`  ✅ Tie-breaker passed!`);
          }
        } else {
          console.log(`  ✅ Ranking order passed!`);
        }
      }

      if (pass && restaurants.length > 0) {
        console.log('\n🎉 ALL RANKING ASSERTIONS PASSED!');
      } else if (restaurants.length === 0) {
        console.warn('\n⚠️ No restaurants returned. Ensure you have seeded the database or run in Mock DB mode.');
      } else {
        console.error('\n❌ SOME RANKING ASSERTIONS FAILED.');
      }

    } catch (err) {
      console.error('Test execution failed:', err);
    } finally {
      server.close(() => {
        console.log('\nTest server shut down.');
        if (prisma && typeof prisma.$disconnect === 'function') {
          prisma.$disconnect();
        }
        process.exit(0);
      });
    }
  });
}

main();
